### ISSUE TITLE
UnifiCS failing with "Error while trying to update aps: string indices must be integers, not 'str'"

### ISSUE THREAD

**Issue by elarsson1** [clyra/unifics#29]
Since updating Home Assistant from 2023.12.2 to 2023.12.3, updates to UnifiCS start failing minutes to several hours after Home Assistant is started. I am seeing the following in the HA log.

After seeing this error, the sensor stops updating. Restarting Home Assistant resumes updating the sensor. 

This error originated from a custom integration.

Logger: custom_components.unifics.sensor
Source: custom_components/unifics/sensor.py:179
Integration: Unifi Counter Sensor
First occurred: 12:28:31 PM (85 occurrences)
Last logged: 1:10:31 PM

Error while trying to update aps: string indices must be integers, not 'str'

**Comment by jkfranks9** [comment]
I've been seeing this problem also. To debug I first determined the number of entries returned in the aps variable in `update_all` in sensor.py, which for me (before the errors start happening) is 3. I then added an if statement to log what is returned when the length of aps is less than 3:

```
    def update_all(self):
        try:
            aps = self.coordinator.data['aps']
            if len(aps) < 3:
                _LOGGER.error("JKF: aps: %s", aps)
            wlans = self.coordinator.data['wlans']
            clients = self.coordinator.data['clients']
```

This is what I then see in the log (note a previous timeout and recovery):

```
2023-12-27 11:06:24.937 ERROR (MainThread) [custom_components.unifics.sensor] Timeout fetching sensor data
2023-12-27 11:06:55.047 INFO (MainThread) [custom_components.unifics.sensor] Fetching sensor data recovered
...
2023-12-27 12:41:01.994 ERROR (MainThread) [custom_components.unifics.sensor] JKF: aps: {'error': {'code': 401, 'message': 'Unauthorized'}}
2023-12-27 12:41:01.995 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
2023-12-27 12:41:01.999 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/unifics/sensor.py", line 174, in update_all
    ap_names = dict([(ap['mac'], ap.get('name', ap['mac'])) for ap in aps])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifics/sensor.py", line 174, in <listcomp>
    ap_names = dict([(ap['mac'], ap.get('name', ap['mac'])) for ap in aps])
                      ~~^^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/unifics/sensor.py", line 263, in state
    self.update_all()
  File "/config/custom_components/unifics/sensor.py", line 182, in update_all
    _LOGGER.error("AP: %s", ap)
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'ap' where it is not associated with a value
```

Not sure why the unauthorized error is happening, but once it does it happens every update cycle, until HA is restarted.

Also, the error handling in this method needs a little work, as can be seen by the secondary error that occurs.

**Comment by clyra** [comment]
Hi,

Usually this happens when the controller returns invalid data to the integration, like no AP list. Do you have the full debug log?

**Comment by jkfranks9** [comment]
I enabled debug for custom_components.unifics_sensor and got this:

```
	Line    54: 2023-12-27 19:05:28.311 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 1.856 seconds (success: True)
	Line   327: 2023-12-27 19:06:00.170 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 1.919 seconds (success: True)
	...
	Line   880: 2023-12-27 19:07:00.342 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.121 seconds (success: True)
	Line   882: 2023-12-27 19:07:30.331 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.118 seconds (success: True)
	Line  1158: 2023-12-27 21:05:07.356 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.143 seconds (success: True)
	Line  1159: 2023-12-27 21:05:37.292 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.079 seconds (success: True)
	Line  1160: 2023-12-27 21:05:37.292 ERROR (MainThread) [custom_components.unifics.sensor] JKF: aps: {'error': {'code': 401, 'message': 'Unauthorized'}}
	Line  1161: 2023-12-27 21:05:37.293 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
	Line  1198: 2023-12-27 21:06:07.241 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.027 seconds (success: True)
	Line  1199: 2023-12-27 21:06:07.242 ERROR (MainThread) [custom_components.unifics.sensor] JKF: aps: {'error': {'code': 401, 'message': 'Unauthorized'}}
	Line  1200: 2023-12-27 21:06:07.243 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
```

But this doesn't add anything new.

Is there something else I can do to get more debug information?

**Comment by andonevris** [comment]
**HA**
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2 

**UNIFI**
UDM Pro
UniFi Network Application 8.0.24


Getting the same issue and logs are pretty much identical

```
Logger: homeassistant
Source: custom_components/unifics/sensor.py:180
Integration: Unifi Counter Sensor
First occurred: 13:10:33 (828 occurrences)
Last logged: 16:40:43
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/unifics/sensor.py", line 172, in update_all
    ap_names = dict([(ap['mac'], ap.get('name', ap['mac'])) for ap in aps])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifics/sensor.py", line 172, in <listcomp>
    ap_names = dict([(ap['mac'], ap.get('name', ap['mac'])) for ap in aps])
                      ~~^^^^^^^
TypeError: string indices must be integers, not 'str'

```

**Comment by nicx** [comment]
+1

**Comment by clyra** [comment]
Hi guys,

Ok... your controller is returning something that is not a proper mac address. I will write code to deal with this situation.

**Comment by clyra** [comment]
Hi @jkfranks9 

Check your credentials. The logs shows unauthorized requests (JKF: aps: {'error': {'code': 401, 'message': 'Unauthorized'}}. Since you said that it works and then fails after some time, maybe you are hitting some kind of rate limit of the controller? The controller has a dinamic or static ip?

**Comment by clyra** [comment]
@nicx, @andonevris 

What logs says in "raw data aps:"?  (take care to remove sensitive data before paste)

**Comment by andonevris** [comment]
> @nicx, @andonevris
> 
> What logs says in "raw data aps:"? (take care to remove sensitive data before paste)

I've just dumped some debug logs, not seeing anything regarding "raw data aps"  where can I find this info?

**Comment by jkfranks9** [comment]
@andonevris, @clyra 

You won't be able to see the "raw data aps" log because the code blows up trying to handle the exception resulting from the original error. 

```
        except Exception as e:
            _LOGGER.error("Error while trying to update aps: %s", e)
            _LOGGER.error("AP: %s", ap)
            _LOGGER.error("raw data aps: %s", aps)
```

The second line above is what is causing the secondary exception shown in the previous logs, which is before the line that shows the raw data aps.

**Comment by jkfranks9** [comment]
FYI, the OP indicated that the problem showed up when updating from 2023.12.2 to 2023.12.3. As a test I downgraded to 2023.12.2 and still see the same problem.

I don't think this has to do with Unifi rate limiting, since it always starts working again after a reboot of HA.

**Comment by clyra** [comment]
The integration uses few resources from HA so I didnt expect it to break with the upgrade.  I'm running it on the newest 2024.1.0 right now. The 401 code comes from the controller, so i dont think there's something the integration can do. @jkfranks9 may you change the line "update_interval=timedelta(seconds=30)" on sensor.py to, let's say 60 seconds? (I should make it a config option...)

**Comment by elarsson1** [comment]
Hi folks, just coming back to this after a break.

FWIW, I have an automation calling homeassistant.reload_config_entry on the sensor entity_id every 20 minutes, which reloads the integration. With this hack, the sensor is being updated. Since the integration reload is instantaneous, I'm less inclined to think that this is persistent throttling from the Unifi Controller that is causing this. Otherwise, I would expect we would continue to get 401s back once the integration reloaded.. no different then any other polling cycle. If only an HA restart cleared the issue, I could see that. The restart delay might be enough that the throttling bucket the controller is empty and it starts accepting requests again.

I see the exception is being thrown in update_all, which is called when the entity state is retrieved, but the actual calls to the Unifi Controller are happening in the async update coordinator thread in async_update_data. Although the behavior appears to be that once we get the first 401 from the controller all subsequent calls fail until the integration or HA is reloaded, we don't actually know from the logs that is what's happening. The subsequent exceptions could be on stale data. I'm wondering if either the initial 401 the update coordinator is getting wedged, or the exception being thrown in update_all is causing HA to kill the update coordinator. (I'm new to HA development, so I may be getting the expected HA behavior wrong here). 

I'm going to try to add some logging to the actual async_update_data method to see if it continues to run after the first error. If not, that suggests that error handling and retry logic needs to move into async_update_data.. If the updates are actually happening, and we are in fact repeatedly getting a 401 back from the controller after the first one occurs, but a reload magically fixes it, then will need to look deeper into what's happening inside pyunifi. Perhaps a symptom of HTTP keepalive, where Unifi persistently returns a 401 on the same HTTP connection once the first is encountered, and reloading the integration effectively forces new connection setup.

**Comment by clyra** [comment]
I just did a small update to the sensor. Should not solve the problem but it will handle exceptions a little better.  @elarsson1 hm... you may be right. I'm kind new to async stuff and in particular to how the HA does that.

**Comment by clyra** [comment]
@elarsson1 I'm thinking about writing a proper coordinator class and handle the calls to the api there. Perhaps calling the three endpoints in one place instead of creating a job for each should solve the problem.

**Comment by jkfranks9** [comment]
@clyra

FYI, testing with your exception handling fix is certainly much better to look at:

```
2024-01-05 10:59:06.627 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.118 seconds (success: True)
2024-01-05 10:59:51.623 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.113 seconds (success: True)
2024-01-05 11:00:36.807 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.298 seconds (success: True)
...
2024-01-05 11:01:21.572 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.062 seconds (success: True)
2024-01-05 11:01:21.573 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
2024-01-05 11:01:21.576 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update wlans: 'str' object has no attribute 'get'
2024-01-05 11:01:21.578 ERROR (MainThread) [custom_components.unifics.sensor] client: error
2024-01-05 11:02:06.534 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.024 seconds (success: True)
2024-01-05 11:02:06.534 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
2024-01-05 11:02:06.536 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update wlans: 'str' object has no attribute 'get'
2024-01-05 11:02:06.538 ERROR (MainThread) [custom_components.unifics.sensor] client: error
```

Thanks!

**Comment by clyra** [comment]
Hi all,

Another update. The integration needs to call 3 endpoints of the unifi controller to gather all the information needed, but it was doing that using 3 different coordinator jobs, which as @elarsson1 pointed could led to using stale data. I changed the code to use just one coordinator job. Please test...

**Comment by jkfranks9** [comment]
Still fails: this occurred about 2 hours after rebooting HA with your fix.

```
2024-01-06 15:49:29.551 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.059 seconds (success: True)
2024-01-06 15:49:29.552 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
2024-01-06 15:49:29.554 ERROR (MainThread) [custom_components.unifics.sensor] raw data aps: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-06 15:49:29.556 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update wlans: 'str' object has no attribute 'get'
2024-01-06 15:49:29.559 ERROR (MainThread) [custom_components.unifics.sensor] raw data wlans: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-06 15:49:29.560 ERROR (MainThread) [custom_components.unifics.sensor] client: error
2024-01-06 15:49:29.562 ERROR (MainThread) [custom_components.unifics.sensor] raw data aps: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-06 15:49:29.564 ERROR (MainThread) [custom_components.unifics.sensor] raw data wlans: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-06 15:49:29.565 ERROR (MainThread) [custom_components.unifics.sensor] raw data clients: {'error': {'code': 401, 'message': 'Unauthorized'}}
```

Started working normally after another HA reboot.

**Comment by jkfranks9** [comment]
Just saw this in my logs. The raw data aps and wlan look normal, but raw data clients has an error:

```
2024-01-07 12:48:57.207 ERROR (MainThread) [custom_components.unifics.sensor] raw data clients: {'timestamp': '2024-01-07T17:48:57Z', 'status': 500, 'error': 'Internal Server Error', 'path': '/api/s/default/stat/sta'}
```

After this error, the integration recovered and kept reporting normally. No reboot required.

**Comment by clyra** [comment]
@jkfranks9 How many devices do you have? If you have too many, maybe changing the polling time should help.

**Comment by jkfranks9** [comment]
I doubled the polling interval to 90, but no luck.

Oddly, I just checked my saved logs, and (at least) the last 6 times this has failed, it started happening almost exactly 2 hours after a reboot. Perhaps it's just that whatever is causing the original error just happens at that interval.

But if the error is actually transient, then unifics should recover at some point instead of continuing to fail.

I'm going to try the automation that @elarsson1 uses, to see if the 2 hour thing still happens without HA reboots.

**Comment by clyra** [comment]
@jkfranks9 I'm a bit confused... you said "After this error, the integration recovered and kept reporting normally. No reboot required.", so after 2 hours you have to reboot to make the integration works again or not? After the last upgrade I would expect that the integration would fail to polling here and there, but continues to work.

**Comment by clyra** [comment]
The error after 2 hours sugests this is the default token/login time. The unifi library should be able to deal with the 401 error by re-authenticating itself, but it doesnt seem to happens for you.... A very crude fix should be to explicit include a re-login try on polling failure. @jkfranks9 may you try to include a line like: client._login() on the exception of api_wrapper? (line 64).

**Comment by jkfranks9** [comment]
@clyra 

So I've had success with your suggestion of logging in again. Adding the _login() call on the exception path doesn't work, because no exception is raised in api_wrapper (the exception happens in update_all() in sensor.py). But I used a very crude method of checking if the length of any of the returned data is 1 to add the login:

```
try: 
      data["aps"] = client.get_aps()
      data["wlans"] = client.get_wlan_conf()
      data["clients"] = client.get_clients()
        
      if len(data["aps"]) == 1 or len(data["wlans"]) == 1 or len(data["clients"]) == 1:
          _LOGGER.debug("JKF logging in")
          client._login()
    except Exception as e:
        _LOGGER.error("pyunify error: %s", e)
        
    return data
```

Although obviously not the correct fix, adding the _login() call does fix the problem. I see a single failure, then it recovers and goes on normally:

```
2024-01-09 19:58:25.510 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.106 seconds (success: True)
2024-01-09 19:59:10.752 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.348 seconds (success: True)
2024-01-09 19:59:55.447 DEBUG (SyncWorker_9) [custom_components.unifics.api_wrapper] JKF logging in
2024-01-09 19:59:55.447 DEBUG (SyncWorker_9) [pyunifi.controller.Controller] login() as XXXXXX@XXXXX.com
2024-01-09 19:59:57.517 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 2.112 seconds (success: True)
2024-01-09 19:59:57.517 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update aps: string indices must be integers, not 'str'
2024-01-09 19:59:57.520 ERROR (MainThread) [custom_components.unifics.sensor] raw data aps: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-09 19:59:57.521 ERROR (MainThread) [custom_components.unifics.sensor] Error while trying to update wlans: 'str' object has no attribute 'get'
2024-01-09 19:59:57.523 ERROR (MainThread) [custom_components.unifics.sensor] raw data wlans: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-09 19:59:57.524 ERROR (MainThread) [custom_components.unifics.sensor] client: error
2024-01-09 19:59:57.524 ERROR (MainThread) [custom_components.unifics.sensor] raw data clients: {'error': {'code': 401, 'message': 'Unauthorized'}}
2024-01-09 20:00:42.701 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.297 seconds (success: True)
2024-01-09 20:01:27.685 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.282 seconds (success: True)
```

What I don't know is if the 2 hour session timeout is configured somewhere, or if that is something you could detect in the integration. It would be nice not to see any errors at all, since this isn't really an error but a predictable event. But for me, I can always filter out this stuff from my log if there's no way to determine the re-login time period.

**Comment by clyra** [comment]
Hi,

Great! Now we can work on a better detection/recover fix. The 2 hour session timeout seems to be something related to your setup, because it dont happen here. I looked into the unifi controller settings but could not find a session timeout or something like that.

**Comment by myopenflixr** [comment]
> Hi,
> 
> Great! Now we can work on a better detection/recover fix. The 2 hour session timeout seems to be something related to your setup, because it dont happen here. I looked into the unifi controller settings but could not find a session timeout or something like that.

OP here. After reading @clyra's most recent post, I started searching for session timeouts within the controller. I enabled the "Legacy" interface and came across a setting of interest.

First of all, I have a couple basic custom firewall rules.
#1 - Allow Established/Related Traffic
#2 - Drop Invalid Traffic

So (via the Legacy interface), go to Settings (Left Menu)>Routing & Firewall (Left Sub Menu)>Firewall (Top Menu)>Settings (Top Sub Menu). From there, scroll down and there's a section for "State Timeouts". TCP Established was set by default at like 7443 seconds (slightly over 2 hours). This is typically when I begin getting errors and the sensors stop reporting. I just set this to 260000 seconds (slightly over 30 days) to see what happens

I have no idea if this will resolve the issue or even if it's wise to change this setting, but I'm giving it a try.

I just restarted Home Assistant and will report back in a couple of hours with an update.

If anyone wants to chime in on whether they think this might work, or if this is a bad idea altogether, please feel free to let me know!

**Comment by myopenflixr** [comment]
> > Hi,
> > Great! Now we can work on a better detection/recover fix. The 2 hour session timeout seems to be something related to your setup, because it dont happen here. I looked into the unifi controller settings but could not find a session timeout or something like that.
> 
> OP here. After reading @clyra's most recent post, I started searching for session timeouts within the controller. I enabled the "Legacy" interface and came across a setting of interest.
> 
> First of all, I have a couple basic custom firewall rules. #1 - Allow Established/Related Traffic #2 - Drop Invalid Traffic
> 
> So (via the Legacy interface), go to Settings (Left Menu)>Routing & Firewall (Left Sub Menu)>Firewall (Top Menu)>Settings (Top Sub Menu). From there, scroll down and there's a section for "State Timeouts". TCP Established was set by default at like 7443 seconds (slightly over 2 hours). This is typically when I begin getting errors and the sensors stop reporting. I just set this to 260000 seconds (slightly over 30 days) to see what happens
> 
> I have no idea if this will resolve the issue or even if it's wise to change this setting, but I'm giving it a try.
> 
> I just restarted Home Assistant and will report back in a couple of hours with an update.
> 
> If anyone wants to chime in on whether they think this might work, or if this is a bad idea altogether, please feel free to let me know!

Unfortunately, this did not resolve the issue. Started getting 401 errors after 2 hours or so.

**Comment by clyra** [comment]
Hi all,

I did a few changes, so the integration should now "self-healing" after a error. I'm also discarding falied pollings so the counter keeps the old values instead of showing 0 devices. Let me know how this work for you.

**Comment by jkfranks9** [comment]
Works great for me:

```
2024-01-12 16:13:51.188 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.306 seconds (success: True)
2024-01-12 16:14:35.996 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.115 seconds (success: True)
2024-01-12 16:15:20.948 ERROR (SyncWorker_1) [custom_components.unifics.api_wrapper] There was a error while trying to retrieve ['aps', 'wlans', 'clients']
2024-01-12 16:15:20.949 ERROR (SyncWorker_1) [custom_components.unifics.api_wrapper] trying to login again, next poll should work
2024-01-12 16:15:20.950 DEBUG (SyncWorker_1) [pyunifi.controller.Controller] login() as XXXXX@XXXXX.com
2024-01-12 16:15:22.727 ERROR (MainThread) [custom_components.unifics.sensor] Error fetching sensor data: Error communicating with API
2024-01-12 16:15:22.728 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 1.847 seconds (success: False)
2024-01-12 16:16:07.251 INFO (MainThread) [custom_components.unifics.sensor] Fetching sensor data recovered
2024-01-12 16:16:07.251 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.370 seconds (success: True)
2024-01-12 16:16:52.390 DEBUG (MainThread) [custom_components.unifics.sensor] Finished fetching sensor data in 0.509 seconds (success: True)
```

Thanks for the fix!

**Comment by andonevris** [comment]
Working here too.

Thanks [clyra](https://github.com/clyra)

**Comment by clyra** [comment]
Ok guys,

Closing this issue. Re-open if necessary.

**Comment by clyra** [comment]
Ok guys,

Closing this issue. Re-open if necessary.
